apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camphoto-ingress
  annotations:
    # This matches the cert we created in Step 1
    networking.gke.io/managed-certificates: camphoto-cert
    # This must match the name of the Static IP you reserved earlier
    kubernetes.io/ingress.global-static-ip-name: camphoto-ip
spec:
  defaultBackend:
    service:
      name: stats-service-lb
      port:
        number: 80