apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
spec:
  replicas: 1  # How many copies you want
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          # REPLACE THIS with your actual image path from Artifact Registry
          image: us-central1-docker.pkg.dev/project1-472613/my-repo/stats-service:v2
          ports:
            - containerPort: 5000
          env:
            # This tells Kubernetes: "Look inside the secret 'aws-creds' for these values"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_secret_access_key
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-lb
  annotations:
    # This connects the Service to the config we just made
    cloud.google.com/backend-config: '{"default": "my-backend-config"}'
spec:
  # CHANGE THIS from LoadBalancer to NodePort
  type: NodePort
  selector:
    app: stats-service
  ports:
    - port: 80
      targetPort: 5000
